import type { Metadata } from "next";
import { Inter, Patrick_Hand } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
// import Providers from "@/components/Providers";
import { Providers } from "@/lib/providers";
import { DynamicWagmiConnector } from "@dynamic-labs/wagmi-connector";
import { DynamicProvider } from "@/lib/DynamicProvider";

const inter = Patrick_Hand({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DynamicProvider>
        <Providers>
          <DynamicWagmiConnector>
      <body
        className={`${inter.className} bg-[url('/assets/ui/clouds.png')] md:bg-contain backdrop-blur-[1px]`}
      >
        {children}  
      </body>
      </DynamicWagmiConnector>
        </Providers>
      </DynamicProvider>
    </html>
  );
}
